php:
  image: php:7.1-fpm
  working_dir: /app
  expose:
    - 9000
  links:
    - db
  volumes:
    - ./:/app

nginx:
  image: nginx:1.12
  ports:
    - 80:80
  volumes:
    - ./:/app
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

db:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: weather
    MYSQL_USER: weather
    MYSQL_PASSWORD: weather